CC = g++
OPENCV = -L/local/lib/ -lopencv_highgui -lopencv_core -lopencv_imgproc -I/local/include/opencv
all : Train Detect
Train: common.cpp common.hpp TrainDetector_Demo.cpp TrainDetector.cpp TrainDetector.hpp data.hpp data.cpp LearnGAB.cpp LearnGAB.hpp LearnDQT.cpp LearnDQT.hpp
	$(CC) common.cpp data.cpp TrainDetector_Demo.cpp TrainDetector.cpp LearnGAB.cpp LearnDQT.cpp $(OPENCV) -fopenmp -o Train -O3

Detect: common.cpp common.hpp Detect_Demo.cpp TrainDetector.cpp TrainDetector.hpp data.hpp data.cpp LearnGAB.cpp LearnGAB.hpp LearnDQT.cpp LearnDQT.hpp
	$(CC) common.cpp data.cpp Detect_Demo.cpp TrainDetector.cpp LearnGAB.cpp LearnDQT.cpp $(OPENCV) -fopenmp -o Detect -O3
